---
- name: install slapd
  apt:
    update_cache: yes
    name: '{{ item }}'
    state: present
  with_items:
    - slapd
    - ldap-utils
    - phpldapadmin

- name: Pass options to dpkg on run
  dpkg_selections:
    name: slapd
    selection: hold
